# Generated by Django 2.1 on 2019-04-19 19:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mydiary', '0002_auto_20190419_0006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='memories',
            new_name='memory',
        ),
    ]
